### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by TomTranter** [LLNL/echemfem#11]
You need to improve the examples.
Ideally there would be a getting started example (or more) where the process of creating a new simple model, running it and viewing the results is explained.
I would like to see an index for each example with a short description of what it does - and more commenting in the examples themselves.
It would be nice to see these as jupyter notebooks that could form part of your docs
In general docs are very light

**Comment by tlroy** [comment]
We will work on improving the examples. I will try to focus the general discussion on how to improve them here. Here is the current plan:

- [x] Add a tutorial example (with detailed instructions)
- [x] Create index of all examples
- [ ] More commenting within examples themselves

Issue #13 also mentioned the structuring of examples and suggested the use of input files. I will also consider this.

**Comment by tlroy** [comment]
Added an [index of examples](https://software.llnl.gov/echemfem/examples.html) in the documentation

**Comment by tlroy** [comment]
@TomTranter @sudarshanv01 @alizma . I added a detailed demo [here](https://software.llnl.gov/echemfem/demos/flow_reactor.py.html). I chose a problem that includes many of the available features (advection, diffusion, migration, bulk reactions, charge-transfer reactions), but is simple enough while being relevant to our CO2 electrolyzer interest. Please let me know what you think.

**Comment by TomTranter** [comment]
Thanks @tlroy. Demo is good. Nice to have some proper explanations and visuals instead of just scripts. I realize this project is new and quite small and you have your own specific research topics but the name of the package suggests it's quite general to electrochemistry but the scripts are very focused on a specific sub topic. Can you comment on the other applications or make another example for fuel cells or batteries

**Comment by tlroy** [comment]
Thank @TomTranter. I agree that the focus on CO2 electrolysis examples distracts for the generality claim. I made this [flow battery example](https://github.com/LLNL/echemfem/blob/main/examples/simple_flow_battery.py) specifically for this reason. A fuel cell is definitely possible to do with the existing code. For batteries, it would have to be simpler than DFN since echemfem does not have a particle-scale model or concentrated solution theory (I am working on a separate, battery-focused code for this). I will see if we can find the time to add another non-CO2 example.

**Comment by TomTranter** [comment]
If this is on your roadmap that's good enough for me
