### ISSUE TITLE
Installation with Firedrake

### ISSUE THREAD

**Issue by sudarshanv01** [LLNL/echemfem#8]
Hi @tlroy, this issue is with regards to [this](https://github.com/openjournals/joss-reviews/issues/6531#issuecomment-2016035376) review. I am having some trouble with installing `Firedrake`, which seems to be an important dependency for `echemfem`. 

Please correct me if I am mistaken, but to summarize my understanding: `Firedrake` requires root access for accessing the package manager (apt/brew) in order to install required packages. There also appear to be several configuration options to install `Firedrake` through their python installer (with torch, complex, etc). I do not currently see any recommended installation instructions for `Firedrake` within the install instructions of this package. Could there be more explicit options on tags to pass to the `Firedrake` installer? Optionally, to make it easier for users, you may provide a set of required packages that can be installed by apt/brew that is required specifically for the features of `Firedrake` that this package required.

Specifically to my installation troubles, I am attempting to install `Firedrake` on a (clean) ubuntu virtual machine - allowing root access for the installation. With python3.10, the installer fails with an error that it is not able to install vtk (specifically `No matching distribution found for vtk>=9.0.1`). It seems like the only way forward to to change `firedrake-install`, are there any recommendations for what version is needed for `echemfem`?

**Comment by tlroy** [comment]
Hi @sudarshanv01 . Firedrake is indeed crucial for EchemFEM. Installing Firedrake is not necessarily trivial as you have experienced. I am going to try to answer all your questions:
- By default apt/brew is used, but it can be disabled with `--no-package-manager`. This is usually needed when installing on clusters. Making sure all the dependencies are satisfied requires a bit of work.
- The default configuration is good for echemfem. No need for torch, complex, etc. I think most other dependencies are indeed used when running echemfem.
- I can add in the instructions that the default configuration can be used.

As for your specific installation, I have not seen this error yet. Here are some things to try:
- Is your python 32-bit or 64-bit? I think vtk only support 64-bit.
- You can attempt to fix the installation by going in the firedrake venv: 
``` 
source firedrake/bin/activate
pip install vtk==9.0.5
firedrake-update
 ```
 - Instead of installing firedrake, you can use this docker image: https://hub.docker.com/r/firedrakeproject/firedrake

**Comment by sudarshanv01** [comment]
Thanks for the detailed answer! The docker image works fine and I have been able to install the package. A quick follow up to close this thread - do you need editable install with your `pip install` command? An alternative that you may consider is publishing the [package to pypi](https://packaging.python.org/en/latest/tutorials/packaging-projects/).

**Comment by tlroy** [comment]
pypi is a good idea. I will consider doing this alongside the JOSS publication.

**Comment by sudarshanv01** [comment]
Sounds great! I will close this issue and tick the review for 
> Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
once you let me know!

**Comment by TomTranter** [comment]
+1 for more information about installing firedrake in your repo

**Comment by tlroy** [comment]
I added more firedrake installation details in the [QuickStart guide](https://software.llnl.gov/echemfem/quickstart.html#installation).

**Comment by sudarshanv01** [comment]
Looks great!
